name: Build documentation
run-name: "Build documentation #${{ github.run_number }}"

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: docs/p
  # Replace XX with the ID of the instance in capital letters
  ARTIFACT: webHelpP2-all.zip
  # Docker image version
  DOCKER_VERSION: 241.18775

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
          retention-days: 7

  build-api-docs:
    name: Build API docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: 📦 Build API docs using Dokka
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: dokkaHtml
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload API docs
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: |
            build/dokka/html
          retention-days: 7

  build-dist-forms:
    name: Build Distribution Forms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Distribution Forms
        shell: bash
        run: |
          chmod +x .github/create-dist-forms.sh
          .github/create-dist-forms.sh

      - name: Upload API docs
        uses: actions/upload-artifact@v4
        with:
          name: dist-forms
          path: |
            build/install/**
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: ['build-docs', 'build-api-docs', 'build-dist-forms']
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq ${{ env.ARTIFACT }} -d dir

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-docs
          path: dir/api

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-forms
          path: dir/install

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
